[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
totp-lite = "1.0.3"

[dependencies.rusqlite]
version = "0.26.3"
features = ["bundled"]
